# Trigger to filter events to EventTransform
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-event-transform
spec:
  broker: inmem-broker
  filters:
    - prefix:
        type: dev.knative.apiserver.resource.
  subscriber:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: EventTransform
      name: kubevirt-example
